### ISSUE TITLE
Extend SYNTAB hash key with 5-tuple for Duplicate SYN...

### ISSUE THREAD

**Issue by hwnahm** [danielinux/pepsal#3]
Sometimes it happens that SYN is duplicated and packets are dropped.

To moderate this how to use destination ip and port together for making SYNTAB hash key?
I mean using 5-tuple to make hash key for flows.

**Comment by danielinux** [comment]
After many years of inactivity, this repository is now marked as archived.
A more recent branch is currently actively developed and maintained by the
French national space agency (CNES), in compliance with the original license
and goals of the project.

Please refer to their publicly available repository here: https://github.com/CNES/pepsal/
