### ISSUE TITLE
pepsal not getting tcp syn packets

### ISSUE THREAD

**Issue by gabeblack** [danielinux/pepsal#4]
I have three machines:

machine1: lan1 ip 192.168.6.1  <-- will run iperf3 client
machine2: lan1 ip 192.168.1.2    wan1 ip: 192.168.6.2  <--- running pepsal -v
machine3: wan1 ip 192.168.6.3  <--- will run iperf3 server

I ran the iptables-config-example.sh script with "lan1" as the interface to use in the iptables mangle script

After adding a static arp entry on machine1 for remote ip 192.168.6.3 (matching the mac of lan1 on machine2) I then launch an an iperf3 server on machine3, and an iperf3 client on machine1. 

I run tcpdump and see the syn packets arriving on lan1 for machine 2. I see the iptables rule matching the mangling rule (counts go up with every tcpdump syn packet seen on lan1). However, the debug print on pepsal never shows anything other than "Entering lister main loop..."

I do have a wan emulator between machine 2 and machine 3 and it will be set up to simulate a GEO satellite connection. Anyway, I have scoured for documentation on how to configure and set up pepsal  put haven't really found anything. The project is pretty old, so I wasn't sure if it may not work anymore.

**Comment by danielinux** [comment]
After many years of inactivity, this repository is now marked as archived.
A more recent branch is currently actively developed and maintained by the
French national space agency (CNES), in compliance with the original license
and goals of the project.

Please refer to their publicly available repository here: https://github.com/CNES/pepsal/
