### ISSUE TITLE
About the use of tproxy transparent proxy

### ISSUE THREAD

**Issue by jzbg** [danielinux/pepsal#5]
← 

This tool is very good and perfect, it can divide TCP into two parts, but it is not completely transparent, after testing, the client does not feel the existence of PEP, but the message received by the server can perceive the existence of PEP, and the client IP cannot be obtained, how to combine with the TPRroxy tool to achieve complete transparency，can you give me some help？

**Comment by danielinux** [comment]
After many years of inactivity, this repository is now marked as archived.
A more recent branch is currently actively developed and maintained by the
French national space agency (CNES), in compliance with the original license
and goals of the project.

Please refer to their publicly available repository here: https://github.com/CNES/pepsal/
